<?php
namespace Nette;
if (!function_exists(/*Nette\*/'_netteRequestCb2')) {

	function _netteRequestCb2($m)
	{
		return "$m[1]<a href='#' class='nette-toggler'>$m[2]($m[3]) " . '<abbr>&#x25ba;</abbr> </a><code class="nette-hidden">';
	}
}

?>
<style>
/* <![CDATA[ */
/* ]]> */
</style>



<h1>Requests</h1>

<div class="nette-inner">

<table>
	<thead>
	<tr><th>Request</th><th>Details</th><th>Dumps</th></tr>
	</thead>
<?php foreach ($logs as $name => $entry): ?>
	<tr>
		<td><strong><?php echo $entry['request']?></strong></td>
		<td nowrap><?php echo $entry['presenter']?></td>
		<td>
			<a class="nette-toggler" href="#"><abbr>&#x25ba;</abbr></a>
			<table class="nette-hidden">
			<?php foreach ($entry['dumps'] as $key => $dump): ?>
			<tr>
				<td>
					<strong><?php if (!is_numeric($key)) echo $key;?></strong>
				</td>
				<td><?php echo preg_replace_callback('#(<pre class="nette-dump">|\s+)?(.*)\((\d+)\) <code>#', 'Nette\_netteRequestCb2', $dump) ?>

				</td>
			</tr>
			<?php endforeach ?>
			</table>
		</td>
	</tr>
<?php endforeach ?>
</table>

</div>



